GET http://127.0.0.1:8000/get-csrf-token
Accept: application/json
###
DELETE http://127.0.0.1:8000/games/3
X-CSRF-TOKEN: SZ1kDGXhu2nfxbGBxGdBPSm1aAiPFoJwh6TGiJKN

###
GET http://127.0.0.1:8000/
Accept: application/xhtml+xml

### Testing
GET http://127.0.0.1:8000/games/1

###
GET http://127.0.0.1:8000/games/2

###
GET http://127.0.0.1:8000/games/3

###
GET http://127.0.0.1:8000/games/4

###
GET http://127.0.0.1:8000/games/5